name:                semarchbot
version:             0.1.0.0
github:              "schar/semarchbot"
license:             BSD3
author:              "Simon Charlow"
maintainer:          "simoncharlow@gmail.com"
copyright:           "2022 Simon Charlow"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/schar/semarchbot#readme>

dependencies:
- base >= 4.5 && < 5
- bytestring
- case-insensitive
- conduit
- conduit-extra
- containers
- curl
- directory
- filepath
- http-conduit >= 2.3.0
- lens
- MissingH
- network-uri
- process
- resourcet
- scalpel
- split
- text
- transformers
- twitter-conduit
- twitter-types-lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  semarchbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semarchbot
